PINDREAM/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "pages#home"
  get "dreams", to:"pages#notes"
  get "favoris", to:"pages#favoris"
  resources :posts

end

PINDREAM/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

PINDREAM/app/models/page.rb
class Page < ApplicationRecord
end

PINDREAM/app/models/post.rb
class Post < ApplicationRecord
  validates :title, :date_dream, :note, presence: true
end

PINDREAM/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

PINDREAM/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def notes
    @notes = Post.all
  end

  def favoris
    @favoris = Post.where(liked:true)
  end
end

PINDREAM/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_posts, only: [:show, :update, :destroy, :edit]
  def index
    @notes = Post.all
  end

  def new
    @note = Post.new
  end

  def create
    @note = Post.new(posts_params)
    if @note.save
      redirect_to post_path(@note)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def update
    @note.update(posts_params)
    redirect_to post_path(@note)
  end

  def destroy
    @note.destroy
    redirect_to dreams_path, status: :see_other
  end

  def edit
  end

  private

  def set_posts
    @note = Post.find(params[:id])
  end

  def posts_params
    params.require(:post).permit(:title, :note, :date_dream)
  end
end

PINDREAM/app/helpers/application_helper.rb
module ApplicationHelper
end

PINDREAM/app/helpers/pages_helper.rb
module PagesHelper
end

PINDREAM/app/helpers/posts_helper.rb
module PostsHelper
end

PINDREAM/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Pindream" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Pindream">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

PINDREAM/app/views/pages/favoris.html.erb
<% if @favoris.empty? %>
  <p> Aucun rêve est épinglé pour le moment </p>
<% else %>
  <% @favoris.each do |favori| %>
    <%= link_to post_path(favori), note: favori do %>
        <h1><%= note.title %></h1>
        <i><%= note.date_dream %></i>
    <%end%>
  <% end %>
<% end %>
<%= link_to "Retour", dreams_path%>

PINDREAM/app/views/pages/home.html.erb
<h1>Page d'accueil</h1>
<%= link_to "Mes rêves", dreams_path%>
<%= link_to "Retenir un rêve", new_post_path%>
<%= link_to "Mes rêves préférés", favoris_path%>

PINDREAM/app/views/pages/notes.html.erb
<% if @notes.empty?%>
  <p>Aucun rêve enregistré pour le moment</p>
<% else %>
  <% @notes.each do |note| %>
    <%= link_to post_path(note), note: note do %>
        <h1><%= note.title %></h1>
        <i><%= note.date_dream %></i>
    <%end%>
  <% end %>
<% end %>
<%= link_to "Retenir un rêve", new_post_path%>
<%= link_to "Retour", root_path%>
<%= link_to "Voir les rêves épinglés", favoris_path%>
<div>
<iframe
src="https://www.youtube.com/embeb/WJBAP8iu3Lo">
</iframe>
</div>

PINDREAM/app/views/posts/edit.html.erb
<%= form_with model: @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :note %>
  <%= f.text_field :note %>
  <%= f.date_select :date_dream %>
  <%= f.submit "Modifier" %>
<% end %>

PINDREAM/app/views/posts/new.html.erb
<%= form_with model: @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :note %>
  <%= f.text_field :note %>
  <%= f.date_select :date_dream %>
  <%= f.submit "Noter" %>
<% end %>
<%= link_to "Retour", dreams_path%>

PINDREAM/app/views/posts/show.html.erb
<h1><%= @note.title %></h1>
<p><%= @note.note %></p>
<i>Reçu le <%= @note.date_dream%></i>
<%= link_to "Retour", dreams_path%>
<%= link_to "Modifier", edit_post_path(@note)%>
<%= link_to "Supprimer", post_path(@note), data: {turbo_method: :delete, turbo_confirm: "Tu veux oublier ce rêve ?"} %>
<%= link_to favoris_path do %>
  <% @note.liked ? "Retirer des favoris" : "Mettre en favori" %>
<%end%>